/**
 * Insights page — PRD §23, §24, §25, §72.
 * Every card is generated by the deterministic insight engine from verified
 * facts. The "evidence" disclosure exposes the exact numbers behind each
 * sentence, and we explicitly state the engine is rule-based, not generative
 * (PRD §72: "Do not claim generative AI if the engine is deterministic").
 */

import {
  ArrowDownRight,
  ArrowUpRight,
  BadgeInfo,
  Calculator,
  CircleDollarSign,
  Info,
  Lightbulb,
  PiggyBank,
  Repeat,
  Target,
  TrendingUp,
  Wallet
} from 'lucide-react'
import { useLedger } from '@/hooks/useLedger'
import type { Insight, InsightKind, InsightTone } from '@/analytics/insightEngine'
import { formatBdt } from '@/lib/money'
import { formatMonthKey } from '@/lib/dates'
import { Badge, Disclosure, EmptyState, SectionHeader, cx } from '@/components/ui'
import { MonthSelector } from '@/components/AppShell'
import { PageHeading } from './Dashboard'

const KIND_ICON: Record<InsightKind, typeof Lightbulb> = {
  'category-dominance': Target,
  'category-increase': ArrowUpRight,
  'category-decrease': ArrowDownRight,
  'largest-expense': CircleDollarSign,
  'forecast-risk': TrendingUp,
  'forecast-headroom': TrendingUp,
  'savings-capacity': PiggyBank,
  recurring: Repeat,
  pace: Calculator,
  'month-comparison': ArrowUpRight,
  'new-category': BadgeInfo,
  'salary-usage': Wallet,
  'pocket-feasibility': Target,
  'insufficient-data': Info
}

const TONE_STYLES: Record<InsightTone, { card: string; icon: string; badge: 'positive' | 'negative' | 'warning' | 'neutral' }> = {
  positive: { card: 'border-positive-500/25', icon: 'bg-positive-50 text-positive-600', badge: 'positive' },
  warning: { card: 'border-warn-500/25', icon: 'bg-warn-50 text-warn-600', badge: 'warning' },
  critical: { card: 'border-negative-500/30', icon: 'bg-negative-50 text-negative-600', badge: 'negative' },
  neutral: { card: 'border-[var(--border-soft)]', icon: 'bg-ink-100 text-ink-500', badge: 'neutral' }
}

const TONE_LABEL: Record<InsightTone, string> = {
  positive: 'Good',
  warning: 'Watch',
  critical: 'Action needed',
  neutral: 'Context'
}

/** Highlight ৳ amounts and percentages inside the insight sentence (PRD §72). */
function HighlightedBody({ text }: { text: string }) {
  const parts = text.split(/(৳[\d,]+(?:\.\d{2})?|[-+]?\d+(?:\.\d+)?%)/g)
  return (
    <p className="text-sm leading-relaxed text-ink-600">
      {parts.map((part, i) =>
        /^৳|%$/.test(part) && part.length > 1 ? (
          <strong key={i} className="tnum font-semibold text-ink-900">
            {part}
          </strong>
        ) : (
          <span key={i}>{part}</span>
        )
      )}
    </p>
  )
}

function InsightCard({ insight }: { insight: Insight }) {
  const Icon = KIND_ICON[insight.kind] ?? Lightbulb
  const styles = TONE_STYLES[insight.tone]

  return (
    <article className={cx('card card-hover p-5', styles.card)}>
      <div className="flex items-start gap-3.5">
        <div className={cx('flex h-9 w-9 shrink-0 items-center justify-center rounded-xl', styles.icon)}>
          <Icon className="h-4.5 w-4.5" aria-hidden="true" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-sm font-semibold text-ink-900">{insight.title}</h3>
            <Badge tone={styles.badge}>{TONE_LABEL[insight.tone]}</Badge>
          </div>
          <div className="mt-1.5">
            <HighlightedBody text={insight.body} />
          </div>

          {Object.keys(insight.evidence).length > 0 && (
            <details className="group mt-3">
              <summary className="cursor-pointer text-[11px] font-medium text-ink-400 transition-colors hover:text-ink-600">
                Show the numbers behind this
              </summary>
              <dl className="tnum mt-2 grid gap-x-4 gap-y-1 text-[11px] sm:grid-cols-2">
                {Object.entries(insight.evidence).map(([k, v]) => (
                  <div key={k} className="flex items-baseline justify-between gap-2 border-b border-dashed border-ink-100 py-0.5">
                    <dt className="text-ink-400">{humanizeKey(k)}</dt>
                    <dd className="font-medium text-ink-700">{formatEvidence(k, v)}</dd>
                  </div>
                ))}
              </dl>
            </details>
          )}
        </div>
      </div>
    </article>
  )
}

function humanizeKey(k: string): string {
  return k
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .trim()
}

/** Values whose key implies money are rendered as BDT; percents get a %. */
function formatEvidence(key: string, value: string | number | null): string {
  if (value === null) return '—'
  if (typeof value === 'string') return value
  const k = key.toLowerCase()
  if (k.includes('percent') || k.includes('share') || k.includes('ratio')) {
    return k.includes('ratio') ? value.toFixed(3) : `${value}%`
  }
  if (
    k.includes('amount') ||
    k.includes('spend') ||
    k.includes('total') ||
    k.includes('salary') ||
    k.includes('surplus') ||
    k.includes('deficit') ||
    k.includes('difference') ||
    k.includes('current') ||
    k.includes('previous') ||
    k.includes('requested') ||
    k.includes('gap') ||
    k.includes('daily') ||
    k.includes('pending')
  ) {
    return formatBdt(value)
  }
  return String(value)
}

export default function Insights() {
  const { insights, selectedMonth, monthExpenses, forecast, comparison } = useLedger()

  const hasEnoughData = monthExpenses.length > 0

  return (
    <div className="space-y-5">
      <PageHeading
        title="Insights"
        subtitle="Your money, understood."
        action={<MonthSelector />}
      />

      {/* Honesty banner — PRD §72, §73 */}
      <div className="flex gap-2.5 rounded-xl border border-[var(--border-soft)] bg-white px-4 py-3 text-xs leading-relaxed text-ink-500">
        <Lightbulb className="mt-0.5 h-4 w-4 shrink-0 text-brand-500" aria-hidden="true" />
        <span>
          These {insights.length} insights are produced by a{' '}
          <strong className="text-ink-700">deterministic rule engine</strong> reading your actual
          stored expenses for {formatMonthKey(selectedMonth)} — not a language model. Every sentence
          is traceable to the numbers shown under “Show the numbers behind this”, and all of them
          recalculate the moment an expense, your salary or the selected month changes.
        </span>
      </div>

      {!hasEnoughData && insights.some((i) => i.kind === 'insufficient-data') && (
        <div className="card">
          <EmptyState
            icon={<Lightbulb className="h-6 w-6" />}
            title="Add a few more expenses to unlock stronger insights."
            message={`No expenses are recorded for ${formatMonthKey(selectedMonth)} yet. Insights sharpen as soon as there is spending to analyse.`}
          />
        </div>
      )}

      {/* ── Summary strip ────────────────────────────────────────────────── */}
      {hasEnoughData && (
        <div className="grid gap-3 sm:grid-cols-3">
          <MiniStat
            label="Spent this month"
            value={formatBdt(forecast.currentSpend)}
            detail={`${monthExpenses.length} expense${monthExpenses.length === 1 ? '' : 's'}`}
          />
          <MiniStat
            label="Projected month end"
            value={formatBdt(forecast.forecastTotal)}
            detail={`${forecast.confidence.toLowerCase()} confidence`}
          />
          <MiniStat
            label={forecast.forecastMoneyLeft >= 0 ? 'Projected surplus' : 'Projected shortfall'}
            value={formatBdt(Math.abs(forecast.forecastMoneyLeft))}
            detail={
              comparison.percentageChange !== null
                ? `${comparison.percentageChange > 0 ? 'Up' : 'Down'} ${Math.abs(comparison.percentageChange).toFixed(1)}% vs last month`
                : 'No comparison available'
            }
            tone={forecast.forecastMoneyLeft >= 0 ? 'positive' : 'negative'}
          />
        </div>
      )}

      {/* ── Insight cards ────────────────────────────────────────────────── */}
      <div>
        <SectionHeader
          title={`${insights.length} insight${insights.length === 1 ? '' : 's'}`}
          subtitle="Ordered by importance to your current position"
        />
        <div className="grid gap-3 lg:grid-cols-2">
          {insights.map((i) => (
            <InsightCard key={i.id} insight={i} />
          ))}
        </div>
      </div>

      {/* ── Methodology ──────────────────────────────────────────────────── */}
      <Disclosure
        label="How insights are generated"
        icon={<Calculator className="h-4 w-4 text-ink-400" aria-hidden="true" />}
      >
        <div className="space-y-3 text-xs leading-relaxed">
          <p>The pipeline is deliberately one-directional so no number can be hallucinated:</p>
          <pre className="overflow-x-auto rounded-xl border border-[var(--border-soft)] bg-white p-3.5 text-[11px] text-ink-600">
{`raw expenses (Firestore)
   ↓
deterministic analytics  (summary · comparison · forecast · recurring · pockets)
   ↓
verified facts objects   (ForecastFacts · MonthComparison · SavingsFacts)
   ↓
rule engine              (each rule may only read the facts objects)
   ↓
insight sentences        (numbers formatted, never computed, at this stage)`}
          </pre>
          <p>
            <strong className="text-ink-700">Rules currently implemented:</strong> category dominance
            (&gt;20% of spending), category increase (&gt;15%), category decrease (&gt;15%), new
            category, overall month comparison, largest single expense, daily pace versus break-even,
            salary utilisation versus calendar progress, forecast risk / headroom, savings capacity,
            pocket feasibility, recurring merchant detection, and pending recurring bills.
          </p>
          <p>
            Each rule carries a priority so the most consequential findings surface first — a
            projected shortfall always outranks a small category movement.
          </p>
        </div>
      </Disclosure>
    </div>
  )
}

function MiniStat({
  label,
  value,
  detail,
  tone = 'neutral'
}: {
  label: string
  value: string
  detail: string
  tone?: 'neutral' | 'positive' | 'negative'
}) {
  return (
    <div className="card p-4">
      <p className="text-xs font-medium uppercase tracking-wider text-ink-500">{label}</p>
      <p
        className={cx(
          'tnum mt-1.5 text-xl font-semibold',
          tone === 'positive' ? 'text-positive-700' : tone === 'negative' ? 'text-negative-700' : 'text-ink-900'
        )}
      >
        {value}
      </p>
      <p className="mt-0.5 text-xs text-ink-400">{detail}</p>
    </div>
  )
}
