/**
 * What-if simulator — PRD §33, §63, Bonus 3.
 *
 * Pick a category, drag the reduction slider, and the REAL engines re-run on
 * simulated numbers: forecast → surplus → every pocket's completion date → DPS.
 * Nothing is written to Firestore and no actual expense is modified; scenario
 * values are labelled "Scenario" throughout.
 */

import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import {
  ArrowRight,
  FlaskConical,
  Info,
  Plus,
  RotateCcw,
  Sparkles,
  Trash2,
  TrendingUp
} from 'lucide-react'
import { useLedger } from '@/hooks/useLedger'
import { calculateWhatIfScenario, type ScenarioAdjustment } from '@/analytics/whatIf'
import { generateInsights } from '@/analytics/insightEngine'
import { CATEGORIES, type Category } from '@/types'
import { formatBdt } from '@/lib/money'
import { formatMonthKey } from '@/lib/dates'
import { Badge, Disclosure, EmptyState, SectionHeader, cx } from '@/components/ui'
import { MonthSelector } from '@/components/AppShell'
import { PageHeading, CATEGORY_COLORS } from './Dashboard'

export default function WhatIf() {
  const {
    expenses,
    pockets,
    settings,
    selectedMonth,
    today,
    summary,
    monthExpenses,
    comparison,
    recurringGroups
  } = useLedger()

  // Default to the largest category so the page is immediately meaningful.
  const defaultCategory = summary.categories[0]?.category ?? 'Food'
  const [adjustments, setAdjustments] = useState<ScenarioAdjustment[]>([
    { category: defaultCategory, reductionPercent: 25 }
  ])

  const scenario = useMemo(
    () =>
      calculateWhatIfScenario({
        expenses,
        pockets,
        salary: settings.monthlySalary,
        monthKey: selectedMonth,
        today,
        dpsAnnualRatePercent: settings.dpsAnnualRatePercent,
        adjustments
      }),
    [expenses, pockets, settings.monthlySalary, settings.dpsAnnualRatePercent, selectedMonth, today, adjustments]
  )

  // Scenario insights, generated by the same engine on the scenario forecast.
  const scenarioInsights = useMemo(
    () =>
      generateInsights({
        expenses,
        monthExpenses,
        forecast: scenario.scenarioForecast,
        comparison,
        savings: scenario.scenarioSavings,
        recurringGroups,
        scenarioLabel: 'Scenario'
      }).slice(0, 3),
    [expenses, monthExpenses, scenario, comparison, recurringGroups]
  )

  const usedCategories = new Set(adjustments.map((a) => a.category))
  const availableToAdd = summary.categories
    .map((c) => c.category)
    .filter((c) => !usedCategories.has(c))

  const setReduction = (index: number, value: number) => {
    setAdjustments((prev) => prev.map((a, i) => (i === index ? { ...a, reductionPercent: value } : a)))
  }
  const setCategory = (index: number, category: Category) => {
    setAdjustments((prev) => prev.map((a, i) => (i === index ? { ...a, category } : a)))
  }

  if (monthExpenses.length === 0) {
    return (
      <div className="space-y-5">
        <PageHeading title="What if?" subtitle="Test a spending change before you make it." />
        <div className="card">
          <EmptyState
            icon={<FlaskConical className="h-6 w-6" />}
            title="Nothing to simulate yet"
            message={`Record some expenses for ${formatMonthKey(selectedMonth)} and you'll be able to test how cutting a category changes your forecast and savings dates.`}
          />
        </div>
      </div>
    )
  }

  const baseline = scenario.baselineForecast
  const sim = scenario.scenarioForecast

  return (
    <div className="space-y-5">
      <PageHeading
        title="What if?"
        subtitle="Test a spending change before you make it."
        action={<MonthSelector />}
      />

      <div className="flex gap-2.5 rounded-xl border border-brand-500/25 bg-brand-50 px-4 py-3 text-xs leading-relaxed text-brand-800">
        <Info className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
        <span>
          Everything below is a <strong>simulation</strong>. Your actual expenses are never modified
          and nothing is saved — the real engines simply re-run on adjusted numbers.
        </span>
      </div>

      {/* ── Controls ─────────────────────────────────────────────────────── */}
      <div className="card p-5">
        <SectionHeader
          title="Adjust a category"
          subtitle={`Based on ${formatMonthKey(selectedMonth)} spending`}
          action={
            <div className="flex gap-1.5">
              {availableToAdd.length > 0 && (
                <button
                  onClick={() =>
                    setAdjustments((prev) => [
                      ...prev,
                      { category: availableToAdd[0], reductionPercent: 20 }
                    ])
                  }
                  className="btn-secondary btn-sm"
                >
                  <Plus className="h-3 w-3" aria-hidden="true" />
                  Add category
                </button>
              )}
              <button
                onClick={() => setAdjustments([{ category: defaultCategory, reductionPercent: 0 }])}
                className="btn-ghost btn-sm"
              >
                <RotateCcw className="h-3 w-3" aria-hidden="true" />
                Reset
              </button>
            </div>
          }
        />

        <div className="space-y-5">
          {adjustments.map((adj, index) => {
            const actual = scenario.actualCategoryTotals[adj.category] ?? 0
            const simulated = scenario.overrides[adj.category] ?? 0
            return (
              <div key={index} className="rounded-xl border border-[var(--border-soft)] p-4">
                <div className="flex flex-wrap items-center gap-3">
                  <select
                    className="input w-auto min-w-[140px]"
                    value={adj.category}
                    onChange={(e) => setCategory(index, e.target.value as Category)}
                    aria-label="Category to reduce"
                  >
                    {CATEGORIES.map((c) => (
                      <option key={c} value={c} disabled={usedCategories.has(c) && c !== adj.category}>
                        {c}
                      </option>
                    ))}
                  </select>

                  <div className="flex items-baseline gap-2 text-xs">
                    <span className="text-ink-400">Actual</span>
                    <span className="tnum font-semibold text-ink-900">{formatBdt(actual)}</span>
                    <ArrowRight className="h-3 w-3 text-ink-300" aria-hidden="true" />
                    <span className="text-ink-400">Scenario</span>
                    <span className="tnum font-semibold text-brand-700">{formatBdt(simulated)}</span>
                  </div>

                  {adjustments.length > 1 && (
                    <button
                      onClick={() => setAdjustments((prev) => prev.filter((_, i) => i !== index))}
                      className="ml-auto rounded-lg p-1.5 text-ink-400 transition-colors hover:bg-negative-50 hover:text-negative-600"
                      aria-label={`Remove ${adj.category} adjustment`}
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  )}
                </div>

                <div className="mt-4">
                  <div className="flex items-center justify-between">
                    <label htmlFor={`red-${index}`} className="text-xs font-medium text-ink-600">
                      Reduce {adj.category} by
                    </label>
                    <span className="tnum text-sm font-semibold text-ink-900">
                      {adj.reductionPercent}%
                    </span>
                  </div>
                  <input
                    id={`red-${index}`}
                    type="range"
                    min={0}
                    max={100}
                    step={5}
                    value={adj.reductionPercent}
                    onChange={(e) => setReduction(index, Number(e.target.value))}
                    className="mt-2 w-full accent-brand-600"
                    aria-valuetext={`${adj.reductionPercent} percent`}
                    style={{ accentColor: CATEGORY_COLORS[adj.category] }}
                  />
                  <div className="mt-1 flex justify-between text-[10px] text-ink-400">
                    <span>0% (no change)</span>
                    <span>50%</span>
                    <span>100% (eliminate)</span>
                  </div>
                </div>
              </div>
            )
          })}
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl bg-positive-50 px-4 py-3">
          <Sparkles className="h-4 w-4 shrink-0 text-positive-600" aria-hidden="true" />
          <p className="text-sm text-positive-800">
            Monthly saving from this change:{' '}
            <strong className="tnum">{formatBdt(scenario.monthlySaving)}</strong>
          </p>
        </div>
      </div>

      {/* ── Forecast comparison ─────────────────────────────────────────── */}
      <div className="grid gap-4 sm:grid-cols-3">
        <CompareCard
          label="Forecast month-end spending"
          before={baseline.forecastTotal}
          after={sim.forecastTotal}
          lowerIsBetter
        />
        <CompareCard
          label={
            baseline.forecastMoneyLeft >= 0 && sim.forecastMoneyLeft >= 0
              ? 'Forecast month-end surplus'
              : 'Forecast position'
          }
          before={baseline.forecastMoneyLeft}
          after={sim.forecastMoneyLeft}
        />
        <CompareCard
          label="Available savings capacity"
          before={baseline.forecastSurplus}
          after={sim.forecastSurplus}
        />
      </div>

      {/* ── Pocket impact table (PRD §33) ────────────────────────────────── */}
      <div className="card overflow-hidden">
        <div className="p-5 pb-4">
          <SectionHeader
            title="Impact on every savings pocket"
            subtitle="Completion dates recalculated from the scenario surplus"
          />
        </div>

        {scenario.pocketDeltas.length === 0 ? (
          <EmptyState
            icon={<TrendingUp className="h-6 w-6" />}
            title="No savings pockets yet"
            message="Create a pocket and you'll see exactly how many months a spending cut would save you."
            action={
              <Link to="/savings" className="btn-accent btn-sm">
                Create savings pocket
              </Link>
            }
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <caption className="sr-only">Scenario impact per savings pocket</caption>
              <thead>
                <tr className="border-y border-[var(--border-soft)] bg-ink-50/60 text-left text-xs font-medium uppercase tracking-wider text-ink-500">
                  <th scope="col" className="px-4 py-2.5">Pocket</th>
                  <th scope="col" className="px-4 py-2.5">Current date</th>
                  <th scope="col" className="px-4 py-2.5">Scenario date</th>
                  <th scope="col" className="px-4 py-2.5">Improvement</th>
                  <th scope="col" className="px-4 py-2.5 text-right">Monthly funding</th>
                  <th scope="col" className="px-4 py-2.5 text-right">DPS value</th>
                </tr>
              </thead>
              <tbody>
                {scenario.pocketDeltas.map((d) => {
                  const improved = (d.monthsEarlier ?? 0) > 0
                  const worse = (d.monthsEarlier ?? 0) < 0
                  return (
                    <tr
                      key={d.pocketId}
                      className="border-b border-[var(--border-soft)] last:border-0 hover:bg-ink-50/60"
                    >
                      <td className="px-4 py-3 font-medium text-ink-900">{d.name}</td>
                      <td className="px-4 py-3 text-ink-500">
                        {d.baselineCompletionMonth
                          ? formatMonthKey(d.baselineCompletionMonth, true)
                          : d.baselineLabel}
                      </td>
                      <td
                        className={cx(
                          'px-4 py-3 font-medium',
                          improved ? 'text-positive-700' : 'text-ink-700'
                        )}
                      >
                        {d.scenarioCompletionMonth
                          ? formatMonthKey(d.scenarioCompletionMonth, true)
                          : d.scenarioLabel}
                      </td>
                      <td className="px-4 py-3">
                        <Badge tone={improved ? 'positive' : worse ? 'negative' : 'neutral'}>
                          {d.improvementLabel}
                        </Badge>
                      </td>
                      <td className="tnum px-4 py-3 text-right text-ink-600">
                        {formatBdt(d.baselineSustainable)}
                        {d.scenarioSustainable !== d.baselineSustainable && (
                          <>
                            {' → '}
                            <span className="font-semibold text-brand-700">
                              {formatBdt(d.scenarioSustainable)}
                            </span>
                          </>
                        )}
                      </td>
                      <td className="tnum px-4 py-3 text-right text-ink-600">
                        {d.scenarioDpsFinalValue !== null ? formatBdt(d.scenarioDpsFinalValue) : '—'}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}

        {scenario.pocketDeltas.length > 0 && scenario.monthlySaving > 0 && scenario.pocketDeltas.every((d) => (d.monthsEarlier ?? 0) === 0) && (
          <p className="border-t border-[var(--border-soft)] px-4 py-3 text-xs leading-relaxed text-ink-500">
            Your pockets don’t move because your planned contributions already fit inside the current
            forecast surplus — the extra cash from this cut isn’t the binding constraint. Raise a
            contribution on the{' '}
            <Link to="/savings" className="font-medium text-brand-700 hover:underline">
              Savings page
            </Link>{' '}
            to convert the freed money into an earlier date.
          </p>
        )}
      </div>

      {/* ── Scenario insights ───────────────────────────────────────────── */}
      <div className="card p-5">
        <SectionHeader
          title="How your insights would read"
          subtitle="The same insight engine, run on the scenario numbers"
        />
        <ul className="grid gap-2.5 lg:grid-cols-3">
          {scenarioInsights.map((i) => (
            <li key={i.id} className="rounded-xl border border-brand-500/20 bg-brand-50/40 p-3.5">
              <div className="flex items-start gap-2">
                <Badge tone="brand" className="shrink-0">
                  Scenario
                </Badge>
              </div>
              <p className="mt-2 text-sm font-medium text-ink-900">
                {i.title.replace(/^Scenario:\s*/, '')}
              </p>
              <p className="mt-1 text-xs leading-relaxed text-ink-600">{i.body}</p>
            </li>
          ))}
        </ul>
      </div>

      <Disclosure
        label="How the simulation works"
        icon={<FlaskConical className="h-4 w-4 text-ink-400" aria-hidden="true" />}
      >
        <div className="space-y-3 text-xs leading-relaxed">
          <pre className="overflow-x-auto rounded-xl border border-[var(--border-soft)] bg-white p-3.5 text-[11px] text-ink-600">
{`scenarioCategoryTotal = actualTotal × (100 − reduction%) ÷ 100
                        (clamped to ≥ 0, so spending can never go negative)

           ↓ fed as a category override into the SAME forecast engine

scenarioForecast  → scenarioSurplus
                  → proportional pocket allocation
                  → month-by-month completion simulation
                  → DPS projection at ${settings.dpsAnnualRatePercent.toFixed(2)}%`}
          </pre>
          <p>
            At 0% reduction the scenario is byte-for-byte identical to your actual forecast; at 100%
            the category becomes exactly zero. Only the current month’s category total is adjusted —
            your historical months stay untouched, which is why the model still blends in last
            month’s real pattern.
          </p>
        </div>
      </Disclosure>
    </div>
  )
}

function CompareCard({
  label,
  before,
  after,
  lowerIsBetter
}: {
  label: string
  before: number
  after: number
  lowerIsBetter?: boolean
}) {
  const delta = after - before
  const improved = lowerIsBetter ? delta < 0 : delta > 0
  const changed = Math.abs(delta) >= 1

  return (
    <div className="card p-5">
      <p className="text-xs font-medium uppercase tracking-wider text-ink-500">{label}</p>
      <div className="mt-3 space-y-2">
        <div className="flex items-baseline justify-between gap-2">
          <span className="text-xs text-ink-400">Before</span>
          <span className="tnum text-sm font-medium text-ink-600">{formatBdt(before)}</span>
        </div>
        <div className="flex items-baseline justify-between gap-2">
          <span className="text-xs font-medium text-brand-700">After (scenario)</span>
          <span
            className={cx(
              'tnum text-lg font-semibold',
              !changed ? 'text-ink-900' : improved ? 'text-positive-700' : 'text-negative-700'
            )}
          >
            {formatBdt(after)}
          </span>
        </div>
      </div>
      {changed && (
        <p
          className={cx(
            'tnum mt-2.5 text-xs font-medium',
            improved ? 'text-positive-700' : 'text-negative-700'
          )}
        >
          {delta > 0 ? '+' : '−'}
          {formatBdt(Math.abs(delta), { symbol: true })} {improved ? 'better' : 'worse'}
        </p>
      )}
      {!changed && <p className="mt-2.5 text-xs text-ink-400">No change at this reduction.</p>}
    </div>
  )
}
